### ISSUE TITLE
update popup still not corrected

### ISSUE THREAD

**Issue by Bobbicat** [jimbob88/wheelers-wort-works#49] opened 2019-05-16 11:13 UTC
I purged and reinstalled then ran a completely freshly downloaded version of wheelers-wort-works-ce

...again the update popup indicates wheelers-wort-works NOT **wheelers-wort-works-ce**

I stress - this is from a completely fresh download of wheelers-wort-works-ce_0.1_all.deb
with the .config/wheelers-wort-works-ce file completely removed
and all related files deleted and purged.

This is what someone new to the program would experience.
The update popup generated on a completely fresh install is still incorrect.

**Comment by jimbob88** [comment] 2019-05-16 11:50
The issue is the deb file itself needs to be released with the edited popup. I'll rebuild the `.deb` soon to include the changed popup

**Comment by Bobbicat** [comment] 2019-05-16 11:55
Yes I guessed that must be so. Thanks Jim.

**Comment by jimbob88** [comment] 2019-05-16 16:25
Fixed in version ce-0.1.1

**Closed as completed by jimbob88** 2019-05-16 16:25 UTC
