### ISSUE TITLE
Re: issue #32

### ISSUE THREAD

**Issue by Bobbicat** [jimbob88/wheelers-wort-works#33] opened 2019-04-18 08:55 UTC
I completely removed/purged the operating system Kubuntu1904beta with all its files.
I re-installed the operating system.
I downloaded WWW version 2.4.5.
I installed WWW using QApt (a .deb installer).
I ran:
`sudo wheelers-wort-works --coreupdate`

The expected 

> ~/.config/Wheelers-Wort-Works

 folder is **not** created during install.
Thus all the errors reported in Issue #32 are still thrown up.
The bug is not fixed.

**Comment by jimbob88** [comment] 2019-04-18 09:57
The issue is that you're using a GUI installer which isn't installing the deb file in a common way (i.e. not running `sudo apt install ./x.deb`) and so the post-installation script is not being run. I'd recommend installing via the command-line for the moment ( i am working on a fix but it is one hell of a job now Ubuntu has deprecated gksu/gksudo)

**Comment by jimbob88** [comment] 2019-04-18 10:06
Fixed in `2.4.6` requires purge and deletion of `~/config/Wheelers-wort-Works`

**Closed as completed by jimbob88** 2019-04-18 10:06 UTC
